# Generated by Django 5.2.5 on 2025-08-31 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, help_text='Company code like ULTRACEMCO', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Full company_name', max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('key_points', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='QueryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('query', models.TextField(help_text='query')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('table_fetched', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('companies_targeted', models.JSONField(help_text='List of company slugs to scrape')),
                ('table_types_targeted', models.JSONField(help_text='List of table types to scrape')),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='started', max_length=20)),
                ('companies_completed', models.JSONField(default=list, help_text='Companies successfully scraped')),
                ('companies_failed', models.JSONField(default=list, help_text='Companies that failed')),
                ('tables_created', models.IntegerField(default=0)),
                ('metrics_extracted', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraping_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
                ('actual_response', models.TextField()),
                ('expected_response', models.TextField()),
                ('query_status', models.CharField(max_length=30)),
                ('issues', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDataTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_type', models.CharField(choices=[('balance-sheet', 'Balance Sheet'), ('profit-loss', 'Profit & Loss'), ('cash-flow', 'Cash Flow'), ('quarters', 'Quarterly Results'), ('ratios', 'Financial Ratios'), ('peers', 'Peer Comparison'), ('shareholding', 'Shareholding Pattern'), ('company-info', 'Company Info')], db_index=True, max_length=50)),
                ('data_type', models.CharField(choices=[('consolidated', 'Consolidated'), ('standalone', 'Standalone')], db_index=True, default='default', max_length=20)),
                ('column_headers', models.JSONField(default=list, help_text="List of column headers like ['Mar 2014', 'Mar 2015', 'Mar 2016', ...]")),
                ('table_data', models.JSONField(default=list, help_text="Array of rows: [['Row Header', 'Cell1', 'Cell2', ...], [...]]")),
                ('total_columns', models.IntegerField(default=0, help_text='Number of columns in table')),
                ('total_rows', models.IntegerField(default=0, help_text='Number of rows in table')),
                ('table_title', models.CharField(blank=True, help_text='Title of the table section', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or context', null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_tables', to='Main.company')),
            ],
            options={
                'db_table': 'financial_data_tables',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyFinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, help_text="Name of the metric like 'Sales', 'Net Profit', 'ROCE %'", max_length=150)),
                ('metric_category', models.CharField(blank=True, help_text="Category like 'Revenue', 'Profitability', 'Ratios'", max_length=100, null=True)),
                ('period', models.CharField(help_text="Time period like 'Mar 2025', 'Q1 2025', 'TTM'", max_length=50)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('ttm', 'TTM'), ('other', 'Other')], default='annual', max_length=20)),
                ('raw_value', models.CharField(help_text='Original value as scraped', max_length=100)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, help_text='Numeric value if parseable', max_digits=25, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit like %, ₹, Cr., times', max_length=20, null=True)),
                ('row_index', models.IntegerField(help_text='Row position in source table')),
                ('column_index', models.IntegerField(help_text='Column position in source table')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_metrics', to='Main.company')),
                ('parent_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Main.keyfinancialmetric')),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_metrics', to='Main.financialdatatable')),
            ],
            options={
                'db_table': 'key_financial_metrics',
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Closing stock price on this date', max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_price_history', to='Main.company')),
            ],
            options={
                'db_table': 'stock_price_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TableDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_column_headers', models.JSONField()),
                ('archived_table_data', models.JSONField()),
                ('archived_total_columns', models.IntegerField()),
                ('archived_total_rows', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_scraped_at', models.DateTimeField()),
                ('archive_reason', models.CharField(default='Data Update', max_length=100)),
                ('original_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Main.financialdatatable')),
            ],
            options={
                'db_table': 'table_data_history',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialdatatable',
            index=models.Index(fields=['company', 'table_type', 'data_type'], name='financial_d_company_faeb71_idx'),
        ),
        migrations.AddIndex(
            model_name='financialdatatable',
            index=models.Index(fields=['table_type', 'scraped_at'], name='financial_d_table_t_64eb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialdatatable',
            index=models.Index(fields=['company', 'scraped_at'], name='financial_d_company_a69b5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialdatatable',
            unique_together={('company', 'table_type', 'data_type')},
        ),
        migrations.AddIndex(
            model_name='keyfinancialmetric',
            index=models.Index(fields=['company', 'metric_name', 'period'], name='key_financi_company_695d25_idx'),
        ),
        migrations.AddIndex(
            model_name='keyfinancialmetric',
            index=models.Index(fields=['metric_name', 'period'], name='key_financi_metric__04e740_idx'),
        ),
        migrations.AddIndex(
            model_name='keyfinancialmetric',
            index=models.Index(fields=['company', 'period_type'], name='key_financi_company_f031f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keyfinancialmetric',
            unique_together={('company', 'metric_name', 'period', 'source_table')},
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together={('company', 'date')},
        ),
    ]
