# Generated by Django 5.2.6 on 2025-10-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies2',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('about_company', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('key_points', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'companies_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialDataTables2',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('table_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=20)),
                ('column_headers', models.JSONField()),
                ('table_data', models.JSONField()),
                ('total_columns', models.IntegerField()),
                ('total_rows', models.IntegerField()),
                ('table_title', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'financial_data_tables_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyFinancialMetrics2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.TextField(blank=True, null=True)),
                ('metric_category', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('period_type', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('row_index', models.BigIntegerField(blank=True, null=True)),
                ('column_index', models.BigIntegerField(blank=True, null=True)),
                ('extracted_at', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('source_table_id', models.TextField(blank=True, null=True)),
                ('parent_relation_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'key_financial_metrics_2',
                'managed': False,
            },
        ),
    ]
