# Generated by Django 5.2.6 on 2025-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_companies2_financialdatatables2_keyfinancialmetrics2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('metric_name', models.CharField(max_length=100)),
                ('significance', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'transformed_data',
            },
        ),
    ]
